version: '3.1'

services:

  sa_api_gateway_app:
    build:
      context: ../
      dockerfile: .dockers/Dockerfile
    container_name: sa_api_gateway_app
    environment:
      TZ: America/Hermosillo
    volumes:
      - ../:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - saloncito
      - sa_api_gateway_network

networks:
  saloncito:
    external: true
  sa_api_gateway_network:
    driver: bridge